# Generated by Django 5.1 on 2024-12-10 15:51

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('date', models.DateTimeField()),
                ('amount', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='PersonOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=192)),
                ('card_number', models.CharField(max_length=16)),
                ('card_currency', models.CharField(choices=[('USD', 'Долар США'), ('EUR', 'Євро'), ('UAH', 'Гривня')], max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=16)),
                ('pin', models.CharField(max_length=4)),
                ('cvv', models.CharField(max_length=3)),
                ('currency', models.CharField(choices=[('USD', 'Долар США'), ('EUR', 'Євро'), ('UAH', 'Гривня')], max_length=64)),
                ('amount_money', models.FloatField(default=0)),
                ('operations', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='paydesk.operation')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itn', models.CharField(max_length=10)),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('age', models.IntegerField(validators=[django.core.validators.MinValueValidator(14), django.core.validators.MaxValueValidator(122)])),
                ('phone_number', models.CharField(max_length=14)),
                ('accounts', models.ManyToManyField(blank=True, related_name='persons', to='paydesk.account')),
            ],
        ),
        migrations.AddField(
            model_name='operation',
            name='recipient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_operations', to='paydesk.personoperation'),
        ),
        migrations.AddField(
            model_name='operation',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sended_operations', to='paydesk.personoperation'),
        ),
    ]
